POST http://localhost:3000/todos
Content-Type: application/json

{
  "text" : "Segundo criado com REST Client.",
  "Completed" : false
}

###

GET http://localhost:3000/todos
Content-Type: application/json


###

GET http://localhost:3000/todos/5b1daf41ab58cf2d4c2313a4
Content-Type: application/json



###

DELETE http://localhost:3000/todos/5b1ddafd62527865502a21b6
Content-Type: application/json

###

PATCH http://localhost:3000/todos/5b1de4f24952bf05b54d5b16
Content-Type: application/json

{
  "text" : "Alterado por REST Client.",
  "completed" : true
}

### ================USERS======================

POST http://localhost:3000/users
Content-Type: application/json

{
  "email":"eduardoa@example.com",
  "password":"senha123"
}
###

GET http://localhost:3000/users/me
Content-Type: application/json
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YjFmNDliOGVmYzZhYTBjNmZiNjkyMmQiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTI4Nzc3MTQ0fQ.o2pO-VAm6UEXsl-nPDceNQWj1BPh26B4UalBoOcp37w



### ================HEROKU======================

POST https://arcane-ridge-64929.herokuapp.com/todos
Content-Type: application/json

{
  "text" : "Criado através do RESTClient." 
}

###

GET https://arcane-ridge-64929.herokuapp.com/todos
Content-Type: application/json


