POST http://localhost:3000/todos
Content-Type: application/json

{
  "text" : "Segundo criado com REST Client.",
  "Completed" : false
}

###

GET http://localhost:3000/todos
Content-Type: :application/json


###

### ================USERS======================

POST http://localhost:3000/todos
Content-Type: application/json

{
  
}
